---
title: Sounds for Pixels
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
    index-number: 
    title: 
    navbar_color: 
    permalink: 
    index_number: 
- scope:
    path: games
    type: documents
  values:
    layout: games
    title: 
    release_date: 
    developer: 
    genre: 
    music_genre: 
    featured_instruments: 
posts: 
output: true
uploads: 
email: contact@soundsforpixels.com
description: |
  A music-making, game-playing duo. Here to help you make YOUR game stand out!
baseurl: 
url: soundsforpixels.com
twitter_username: soundsforpixels
instagram_username: soundsforpixels
github_username: TheHeartmann
twitter_feed_limit: 5
blue: 8ce7f9
gold: d3a628
red: E03B45
green: 239F60
brown: 986638
logo_text: <img class="img img-responsive" src="/assets/img/logo/text_horizontal_litFromLeft.png"
  alt="Sounds for Pixels">
logo_chest_only: <img class="img img-responsive" src="/assets/img/logo/logo_border_noText.png"
  alt="Sounds for Pixels">
logo_chest: <img class="img img-responsive" src="/assets/img/logo/logo_border.png"
  alt="Sounds for Pixels">
header_image: <img class="img img-responsive" src="/assets/img/headers/header_blue_slim.png"
  alt="Default header">
lorem_ipsum: Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus
  ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit
  amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
markdown: kramdown
