---
title: Sounds for Pixels
timezone: Europe/Berlin
collections:
  games:
    title: Games
    output: true
  people:
    title: People
    output: false
  posts:
    title: Posts
    output: true
  quotes:
    title: Quotes
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
    title: 
    permalink: 
- scope:
    path: ''
    type: games
  values:
    layout: post
    title: 
    release_date: 
    developer: 
    genre: 
    music_genre: 
    featured_instrument: 
    roles: 
- scope:
    path: ''
    type: quotes
  values:
    layout: quote
    author: 
    publication: 
    url: 
    date: 
- scope:
    path: ''
    type: people
  values:
    layout: post
    profile_image: 
    mail: 
    name: 
    full_name: 
- scope:
    path: ''
    type: posts
  values:
    layout: post
    person: SFP
    game: 
    soundcloud_embed: 
    category: 
posts: 
output: true
uploads: 
email: contact@soundsforpixels.com
description: |
  A music-making, game-playing duo. Here to help you make YOUR game stand out!
baseurl: 
url: http://soundsforpixels.com
twitter_username: soundsforpixels
instagram_username: soundsforpixels
github_username: TheHeartmann
twitter_feed_limit: 5
paginate: 5
paginate_path: "/blog/page:num/"
blue: 8ce7f9
gold: d3a628
red: E03B45
green: 239F60
brown: 986638
logo_text_image: <img class="img img-responsive" src="/uploads/text_horizontal_litFromLeft_compressed.png"
  alt="Sounds for Pixels">
logo_chest_image: <img class="img img-responsive" src="/uploads/logo_border_noText_compressed.png"
  alt="Sounds for Pixels">
logo_image: <img class="img img-responsive" src="/uploads/logo_border_compressed.png"
  alt="Sounds for Pixels">
header_image: <img class="img img-responsive" src="/assets/img/headers/header_blue_slim.png"
  alt="Default header">
lorem_ipsum: Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus
  ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit
  amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
markdown: kramdown
gems:
- jekyll-paginate
