---
title: Sounds for Pixels
timezone: Europe/Berlin
collections:
  games:
    title: Games
    output: false
  people:
    title: People
    output: false
  posts:
    title: Posts
    output: true
  quotes:
    title: Quotes
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
    title: 
    permalink: 
    has_sidebar: false
    sidebar_icon: 
- scope:
    path: ''
    type: games
  values:
    main_image: 
    header_image: 
    layout: game
    title_no_spaces: 
    sc_id: 
    shop_url: 
    shop_name: 
    available_at: 
    yt_id: 
    title: 
    release_date: 
    developer: 
    developer_website: 
    genre: 
    music_genre: 
    featured_instrument: 
    roles: 
- scope:
    path: ''
    type: quotes
  values:
    layout: 
    game: 
    author: 
    publication: 
    quote_url: 
    quote_date: 
- scope:
    path: ''
    type: people
  values:
    layout: post
    profile_image: 
    mail: 
    name: 
    full_name: 
- scope:
    path: ''
    type: posts
  values:
    layout: post
    person: SFP
    game: 
    sc_id:
    - 
    - 
    - 
posts: 
output: true
uploads: 
email: contact@soundsforpixels.com
description: |
  Want music that makes your game pop? Sound effects that brings your characters to life? Look no further: Composer duo Sounds for Pixels are here to help!
footer_text: |
  A music-making, game-playing duo. Here to help you make YOUR game stand out!
baseurl: 
url: http://soundsforpixels.com
twitter_username: soundsforpixels
instagram_username: soundsforpixels
github_username: TheHeartmann
twitter_feed_limit: 5
playlist: <iframe width="100%" height="450" scrolling="no" frameborder="0" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/201824315&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=false&amp;show_reposts=false"></iframe>
blue: 8ce7f9
gold: d3a628
red: E03B45
green: 239F60
brown: 986638
logo_text_image: <img class="img img-responsive" src="/uploads/text_horizontal_litFromLeft_compressed.png"
  alt="Sounds for Pixels">
logo_chest_image: <img class="img img-responsive" src="/uploads/logo_border_noText_compressed.png"
  alt="Sounds for Pixels">
logo_image: <img class="img img-responsive" src="/uploads/logo_border_compressed.png"
  alt="Sounds for Pixels">
header_image: <img class="img img-responsive" src="/assets/img/headers/header_blue_slim.png"
  alt="Default header">
lorem_ipsum: Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus
  ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit
  amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
markdown: kramdown
